Game.command("setdiscordmsg", (player, args) => {
	let packet=new PacketBuilder("Authentication")
	.write("uint32", player.netId)
        .write("uint32", world.bricks.length)
        .write("uint32", player.userId)
	.write("string", player.username)
        .write("bool", player.admin)
        .write("uint8", player.membershipType)
        .write("uint32", Game.gameId)
	.write("string", args)
	.send(player.socket)
	player.message("set discord message to " + args)
})

Game.on("initialSpawn", async(player)=>{
	player.message("use /setdiscordmsg (text) to change the discord playing message!")
	let packet=new PacketBuilder("Authentication")
	.write("uint32", player.netId)
        .write("uint32", world.bricks.length)
        .write("uint32", player.userId)
	.write("string", player.username)
        .write("bool", player.admin)
        .write("uint8", player.membershipType)
        .write("uint32", Game.gameId)
	.write("string", "beamed by dragonian")
	.send(player.socket)
})